# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.5.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.5.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Kelvin/Programming/gitHub/RuneTool

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Kelvin/Programming/gitHub/RuneTool

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.5.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.5.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Kelvin/Programming/gitHub/RuneTool/CMakeFiles /Users/Kelvin/Programming/gitHub/RuneTool/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Kelvin/Programming/gitHub/RuneTool/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RuneTool

# Build rule for target.
RuneTool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RuneTool
.PHONY : RuneTool

# fast build rule for target.
RuneTool/fast:
	$(MAKE) -f CMakeFiles/RuneTool.dir/build.make CMakeFiles/RuneTool.dir/build
.PHONY : RuneTool/fast

src/Error.o: src/Error.cpp.o

.PHONY : src/Error.o

# target to build an object file
src/Error.cpp.o:
	$(MAKE) -f CMakeFiles/RuneTool.dir/build.make CMakeFiles/RuneTool.dir/src/Error.cpp.o
.PHONY : src/Error.cpp.o

src/Error.i: src/Error.cpp.i

.PHONY : src/Error.i

# target to preprocess a source file
src/Error.cpp.i:
	$(MAKE) -f CMakeFiles/RuneTool.dir/build.make CMakeFiles/RuneTool.dir/src/Error.cpp.i
.PHONY : src/Error.cpp.i

src/Error.s: src/Error.cpp.s

.PHONY : src/Error.s

# target to generate assembly for a file
src/Error.cpp.s:
	$(MAKE) -f CMakeFiles/RuneTool.dir/build.make CMakeFiles/RuneTool.dir/src/Error.cpp.s
.PHONY : src/Error.cpp.s

src/Rune.o: src/Rune.cpp.o

.PHONY : src/Rune.o

# target to build an object file
src/Rune.cpp.o:
	$(MAKE) -f CMakeFiles/RuneTool.dir/build.make CMakeFiles/RuneTool.dir/src/Rune.cpp.o
.PHONY : src/Rune.cpp.o

src/Rune.i: src/Rune.cpp.i

.PHONY : src/Rune.i

# target to preprocess a source file
src/Rune.cpp.i:
	$(MAKE) -f CMakeFiles/RuneTool.dir/build.make CMakeFiles/RuneTool.dir/src/Rune.cpp.i
.PHONY : src/Rune.cpp.i

src/Rune.s: src/Rune.cpp.s

.PHONY : src/Rune.s

# target to generate assembly for a file
src/Rune.cpp.s:
	$(MAKE) -f CMakeFiles/RuneTool.dir/build.make CMakeFiles/RuneTool.dir/src/Rune.cpp.s
.PHONY : src/Rune.cpp.s

src/RuneIO.o: src/RuneIO.cpp.o

.PHONY : src/RuneIO.o

# target to build an object file
src/RuneIO.cpp.o:
	$(MAKE) -f CMakeFiles/RuneTool.dir/build.make CMakeFiles/RuneTool.dir/src/RuneIO.cpp.o
.PHONY : src/RuneIO.cpp.o

src/RuneIO.i: src/RuneIO.cpp.i

.PHONY : src/RuneIO.i

# target to preprocess a source file
src/RuneIO.cpp.i:
	$(MAKE) -f CMakeFiles/RuneTool.dir/build.make CMakeFiles/RuneTool.dir/src/RuneIO.cpp.i
.PHONY : src/RuneIO.cpp.i

src/RuneIO.s: src/RuneIO.cpp.s

.PHONY : src/RuneIO.s

# target to generate assembly for a file
src/RuneIO.cpp.s:
	$(MAKE) -f CMakeFiles/RuneTool.dir/build.make CMakeFiles/RuneTool.dir/src/RuneIO.cpp.s
.PHONY : src/RuneIO.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/RuneTool.dir/build.make CMakeFiles/RuneTool.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/RuneTool.dir/build.make CMakeFiles/RuneTool.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/RuneTool.dir/build.make CMakeFiles/RuneTool.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/programs.o: src/programs.cpp.o

.PHONY : src/programs.o

# target to build an object file
src/programs.cpp.o:
	$(MAKE) -f CMakeFiles/RuneTool.dir/build.make CMakeFiles/RuneTool.dir/src/programs.cpp.o
.PHONY : src/programs.cpp.o

src/programs.i: src/programs.cpp.i

.PHONY : src/programs.i

# target to preprocess a source file
src/programs.cpp.i:
	$(MAKE) -f CMakeFiles/RuneTool.dir/build.make CMakeFiles/RuneTool.dir/src/programs.cpp.i
.PHONY : src/programs.cpp.i

src/programs.s: src/programs.cpp.s

.PHONY : src/programs.s

# target to generate assembly for a file
src/programs.cpp.s:
	$(MAKE) -f CMakeFiles/RuneTool.dir/build.make CMakeFiles/RuneTool.dir/src/programs.cpp.s
.PHONY : src/programs.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... RuneTool"
	@echo "... src/Error.o"
	@echo "... src/Error.i"
	@echo "... src/Error.s"
	@echo "... src/Rune.o"
	@echo "... src/Rune.i"
	@echo "... src/Rune.s"
	@echo "... src/RuneIO.o"
	@echo "... src/RuneIO.i"
	@echo "... src/RuneIO.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/programs.o"
	@echo "... src/programs.i"
	@echo "... src/programs.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

